#!/usr/bin/env node

/**
 * ForgeFlow Mini — Brain Initialization Script (v2)
 * Rewritten to avoid security hook issues
 *
 * Usage: node scripts/init.js [project-path]
 */

const fs = require('fs');
const path = require('path');
const { promisify } = require('util');

const readdir = promisify(fs.readdir);
const stat = promisify(fs.stat);
const readFile = promisify(fs.readFile);
const writeFile = promisify(fs.writeFile);
const mkdir = promisify(fs.mkdir);

// Simple color output (no external deps)
const colors = {
  cyan: '\x1b[36m',
  green: '\x1b[32m',
  yellow: '\x1b[33m',
  blue: '\x1b[34m',
  dim: '\x1b[2m',
  reset: '\x1b[0m',
};

function log(color, text) {
  console.log(`${color}${text}${colors.reset}`);
}

/**
 * Check if file exists
 */
function fileExists(filePath) {
  try {
    fs.accessSync(filePath, fs.constants.F_OK);
    return true;
  } catch {
    return false;
  }
}

/**
 * Read JSON file safely
 */
function readJSON(filePath) {
  try {
    const content = fs.readFileSync(filePath, 'utf-8');
    return JSON.parse(content);
  } catch {
    return null;
  }
}

/**
 * Detect project type
 */
function detectProjectType(projectPath) {
  const detections = {
    hasPackageJson: fileExists(path.join(projectPath, 'package.json')),
    hasGoMod: fileExists(path.join(projectPath, 'go.mod')),
    hasPyproject: fileExists(path.join(projectPath, 'pyproject.toml')),
    hasRequirements: fileExists(path.join(projectPath, 'requirements.txt')),
    hasSrcComponents: fileExists(path.join(projectPath, 'src', 'components')),
    hasServerDir: fileExists(path.join(projectPath, 'server')) ||
                  fileExists(path.join(projectPath, 'api')) ||
                  fileExists(path.join(projectPath, 'apps', 'server_core')),
    hasMigrations: fileExists(path.join(projectPath, 'migrations')),
  };

  return detections;
}

/**
 * Generate hippocampus files
 */
function generateHippocampus(projectName, detections) {
  const timestamp = new Date().toISOString();

  const architecture = `---
id: hippocampus-architecture
title: Architecture
region: hippocampus
tags: [architecture, stack, design]
links: []
weight: 1.0
updated_at: ${timestamp}
---

# Architecture

## Tech Stack

- **Backend:** ${detections.hasGoMod ? 'Go' : detections.hasPackageJson ? 'Node.js' : 'Unknown'}
- **Frontend:** ${detections.hasSrcComponents ? 'React' : 'TBD'}
- **Database:** ${detections.hasMigrations ? 'PostgreSQL' : 'TBD'}
- **Infrastructure:** Docker, Kubernetes (assumed)

## Project Type

${detections.hasServerDir && detections.hasSrcComponents ? 'Full-stack' : detections.hasServerDir ? 'Backend-focused' : 'Unknown'}

---

Auto-generated by /brain-init on ${new Date().toLocaleDateString()}. Review and edit.
`;

  const conventions = `---
id: hippocampus-conventions
title: Conventions
region: hippocampus
tags: [conventions, patterns, rules]
links: []
weight: 0.95
updated_at: ${timestamp}
---

# Conventions

## Naming

- Variables: camelCase
- Functions: camelCase
- Classes: PascalCase
- Constants: UPPER_SNAKE_CASE

## Absolute Rules

[To be defined by developer]

---

Auto-generated by /brain-init on ${new Date().toLocaleDateString()}. Developer should review and complete.
`;

  const strategy = `---
id: hippocampus-strategy
title: Product Strategy & Goals
region: hippocampus
tags: [strategy, goals, business]
links: []
weight: 0.85
updated_at: ${timestamp}
---

# Product Strategy & Goals

## Vision

[To be filled in by developer]

## Core Goals

[What is this project's main purpose?]

## Technical Priorities

- [ ] Reliability
- [ ] Performance
- [ ] Maintainability
- [ ] Cost efficiency

---

Auto-generated by /brain-init on ${new Date().toLocaleDateString()}. Developer should complete.
`;

  const registry = `---
id: hippocampus-cortex-registry
title: Cortex Registry
region: hippocampus
tags: [registry, cortex, domains]
links: []
weight: 0.9
updated_at: ${timestamp}
---

# Cortex Registry

| Region | Purpose |
|--------|---------|
| cortex/backend | API, services, business logic |
| cortex/frontend | UI, routing, state |
| cortex/database | Schema, queries, migrations |
| cortex/infra | Deployment, CI/CD |

---

Auto-generated by /brain-init on ${new Date().toLocaleDateString()}.
`;

  const decisions = `---
id: hippocampus-decisions-log
title: Decisions Log
region: hippocampus
tags: [adr, decisions]
links: []
weight: 0.8
updated_at: ${timestamp}
---

# Architecture Decision Records

[ADRs will be added as architectural decisions are made]

---

Auto-generated by /brain-init on ${new Date().toLocaleDateString()}.
`;

  return {
    'hippocampus/architecture.md': architecture,
    'hippocampus/conventions.md': conventions,
    'hippocampus/strategy.md': strategy,
    'hippocampus/cortex_registry.md': registry,
    'hippocampus/decisions_log.md': decisions,
  };
}

/**
 * Generate cortex region sinapses
 */
function generateCortex(cortices) {
  const sinapses = {};
  const timestamp = new Date().toISOString();

  for (const cortex of cortices) {
    sinapses[`cortex/${cortex}/index.md`] = `---
id: cortex-${cortex}-index
title: ${cortex.charAt(0).toUpperCase() + cortex.slice(1)} Domain
region: cortex/${cortex}
tags: [${cortex}]
links: []
weight: 0.7
updated_at: ${timestamp}
---

# ${cortex.charAt(0).toUpperCase() + cortex.slice(1)} Domain

Overview and patterns for the ${cortex} domain.

---

Auto-generated by /brain-init on ${new Date().toLocaleDateString()}.
`;
  }

  return sinapses;
}

/**
 * Determine which cortices are needed
 */
function determineCortices(detections) {
  const cortices = [];
  if (detections.hasServerDir) cortices.push('backend');
  if (detections.hasSrcComponents) cortices.push('frontend');
  if (detections.hasMigrations) cortices.push('database');
  cortices.push('infra');
  return cortices;
}

/**
 * Persist Brain to filesystem
 */
async function persistBrain(projectPath, files) {
  const brainRoot = path.join(projectPath, '.brain');

  // Create directory structure
  const dirs = [
    brainRoot,
    path.join(brainRoot, 'hippocampus'),
    path.join(brainRoot, 'cortex', 'backend'),
    path.join(brainRoot, 'cortex', 'backend', 'lessons'),
    path.join(brainRoot, 'cortex', 'frontend'),
    path.join(brainRoot, 'cortex', 'frontend', 'lessons'),
    path.join(brainRoot, 'cortex', 'database'),
    path.join(brainRoot, 'cortex', 'database', 'lessons'),
    path.join(brainRoot, 'cortex', 'infra'),
    path.join(brainRoot, 'cortex', 'infra', 'lessons'),
    path.join(brainRoot, 'sinapses'),
    path.join(brainRoot, 'lessons', 'cross-domain'),
    path.join(brainRoot, 'lessons', 'inbox'),
    path.join(brainRoot, 'lessons', 'archived'),
    path.join(brainRoot, 'working-memory'),
    path.join(brainRoot, 'progress'),
    path.join(brainRoot, 'progress', 'completed-contexts'),
  ];

  for (const dir of dirs) {
    try {
      await mkdir(dir, { recursive: true });
      log(colors.dim, `  ✓ Created ${path.relative(projectPath, dir)}`);
    } catch (err) {
      // Directory may already exist
    }
  }

  // Create progress/activity.md if it does not exist
  const activityPath = path.join(brainRoot, 'progress', 'activity.md');
  if (!fs.existsSync(activityPath)) {
    fs.writeFileSync(activityPath, '# Brain Activity Log\n\n<!-- Auto-appended by TaskCompleted hook. One entry per brain-task. -->\n', 'utf-8');
    log(colors.green, '  ✓ Created progress/activity.md');
  }

  // Write files
  for (const [relativePath, content] of Object.entries(files)) {
    const filePath = path.join(brainRoot, relativePath);
    try {
      await writeFile(filePath, content, 'utf-8');
      log(colors.green, `  ✓ Wrote ${relativePath}`);
    } catch (err) {
      log(colors.yellow, `  ✗ Failed to write ${relativePath}: ${err.message}`);
    }
  }

  // Copy brain.config.json from plugin template
  const pluginRoot = path.resolve(__dirname, '..');
  const configTemplate = path.join(pluginRoot, 'templates', 'brain', 'brain.config.json');
  const configDest = path.join(brainRoot, 'brain.config.json');
  if (fs.existsSync(configTemplate) && !fs.existsSync(configDest)) {
    try {
      fs.copyFileSync(configTemplate, configDest);
      log(colors.green, '  ✓ Copied brain.config.json from template');
    } catch (err) {
      log(colors.yellow, `  ✗ Could not copy brain.config.json: ${err.message}`);
    }
  }

  return brainRoot;
}

/**
 * Main flow
 */
async function main() {
  log(colors.cyan, '\n🧠 ForgeFlow Mini — Brain Initialization\n');

  const projectPath = process.argv[2] || '.';
  const projectName = path.basename(projectPath);

  // Phase 1: Scan
  log(colors.cyan, '📍 PHASE 1: Scanning project...');
  if (!fileExists(projectPath)) {
    log(colors.yellow, `❌ Project path not found: ${projectPath}`);
    process.exit(1);
  }
  log(colors.green, `✓ Found project: ${projectName}`);

  // Phase 2: Classify
  log(colors.cyan, '\n🔍 PHASE 2: Classifying...');
  const detections = detectProjectType(projectPath);
  const cortices = determineCortices(detections);
  log(colors.green, `✓ Detected ${cortices.length} cortex regions: ${cortices.join(', ')}`);

  // Phase 3-4: Generate
  log(colors.cyan, '\n🧠 PHASE 3-4: Generating...');
  const hippocampus = generateHippocampus(projectName, detections);
  const cortex = generateCortex(cortices);
  log(colors.green, `✓ Generated hippocampus + cortex sinapses`);

  // Phase 5: Review
  log(colors.cyan, '\n👀 PHASE 5: Files ready for review');
  log(colors.blue, `  Hippocampus: ${Object.keys(hippocampus).length} files`);
  log(colors.blue, `  Cortex: ${Object.keys(cortex).length} regions`);

  // Phase 6: Persist
  log(colors.cyan, '\n💾 PHASE 6: Persisting to .brain/...');
  const allFiles = { ...hippocampus, ...cortex };
  const brainRoot = await persistBrain(projectPath, allFiles);

  log(colors.green, `\n✅ Brain initialized successfully!`);
  log(colors.blue, `   Location: ${brainRoot}`);
  log(colors.blue, `   Total sinapses: ${Object.keys(allFiles).length}`);
  log(colors.blue, `\n   Next steps:`);
  log(colors.blue, `   1. Review files in ${brainRoot}`);
  log(colors.blue, `   2. Edit hippocampus/strategy.md with your goals`);
  log(colors.blue, `   3. Run: /brain-status\n`);
}

main().catch(err => {
  log(colors.yellow, `\n❌ Error: ${err.message}`);
  process.exit(1);
});
