-- brain.db — Canonical SQLite Schema
-- Source of truth for all brain-map, brain-consolidate queries.
-- Generated by brain-init Phase 7 (python scripts/build_brain_db.py).
-- If a skill query fails, check this schema first.

----------------------------------------------------------------------
-- SINAPSES — Curated domain knowledge nodes
----------------------------------------------------------------------
-- Each sinapse is a markdown file indexed into this table.
-- Regions map to the .brain/ directory structure:
--   'hippocampus'       → .brain/hippocampus/*.md
--   'cortex/backend'    → .brain/cortex/backend/*.md
--   'cortex/frontend'   → .brain/cortex/frontend/*.md
--   'cortex/database'   → .brain/cortex/database/*.md
--   'cortex/infra'      → .brain/cortex/infra/*.md
--   'sinapses/'         → .brain/sinapses/*.md (cross-cutting)

CREATE TABLE IF NOT EXISTS sinapses (
    id            TEXT PRIMARY KEY,          -- e.g., 'hippocampus-architecture', 'cortex-backend-index'
    file_path     TEXT NOT NULL,             -- relative path from .brain/ root
    title         TEXT NOT NULL,
    region        TEXT NOT NULL,             -- directory-based: 'hippocampus', 'cortex/backend', 'sinapses/'
    tags          TEXT DEFAULT '[]',         -- JSON array of string tags
    links         TEXT DEFAULT '[]',         -- JSON array of related sinapse ids
    content       TEXT,                      -- full markdown content (for search/condensing)
    weight        REAL NOT NULL DEFAULT 0.50,-- 0.0–1.0, higher = more relevant. Adjusted by brain-consolidate.
    last_accessed TEXT,                      -- ISO8601 datetime, updated on each brain-map load
    usage_count   INTEGER NOT NULL DEFAULT 0,-- incremented each time loaded into a context packet
    created_at    TEXT NOT NULL,             -- ISO8601
    updated_at    TEXT NOT NULL              -- ISO8601
);

CREATE INDEX IF NOT EXISTS idx_sinapses_region ON sinapses(region);
CREATE INDEX IF NOT EXISTS idx_sinapses_weight ON sinapses(weight DESC);

----------------------------------------------------------------------
-- SINAPSE_LINKS — Directed edges between sinapses
----------------------------------------------------------------------
-- Represents backlinks / references between knowledge nodes.
-- Used by brain-map Tier 2 (backlink enrichment) and Tier 3 (on-demand expansion).

CREATE TABLE IF NOT EXISTS sinapse_links (
    source_id TEXT NOT NULL,                -- FK → sinapses.id (the sinapse containing the reference)
    target_id TEXT NOT NULL,                -- FK → sinapses.id (the sinapse being referenced)
    PRIMARY KEY (source_id, target_id),
    FOREIGN KEY (source_id) REFERENCES sinapses(id) ON DELETE CASCADE,
    FOREIGN KEY (target_id) REFERENCES sinapses(id) ON DELETE CASCADE
);

CREATE INDEX IF NOT EXISTS idx_sinapse_links_source ON sinapse_links(source_id);
CREATE INDEX IF NOT EXISTS idx_sinapse_links_target ON sinapse_links(target_id);

----------------------------------------------------------------------
-- CONSOLIDATION_LOG — Tracks brain-consolidate runs
----------------------------------------------------------------------
-- One row per consolidation cycle. Used to determine "since last consolidate".

CREATE TABLE IF NOT EXISTS consolidation_log (
    cycle_number   INTEGER PRIMARY KEY AUTOINCREMENT,
    tasks_reviewed INTEGER NOT NULL DEFAULT 0,
    proposals_approved INTEGER NOT NULL DEFAULT 0,
    proposals_rejected INTEGER NOT NULL DEFAULT 0,
    escalations_surfaced INTEGER NOT NULL DEFAULT 0,
    sinapses_reweighted INTEGER NOT NULL DEFAULT 0,
    created_at     TEXT NOT NULL
);

----------------------------------------------------------------------
-- BRAIN_STATE — Key-value store for pipeline state persistence
----------------------------------------------------------------------
-- Secondary persistence layer for brain-state.json.
-- Updated by brain-task at each gate checkpoint.
-- Used for recovery if JSON files get corrupted.

CREATE TABLE IF NOT EXISTS brain_state (
    key        TEXT PRIMARY KEY,
    value      TEXT NOT NULL,
    updated_at TEXT NOT NULL
);

----------------------------------------------------------------------
-- FTS5 — Full-text search indexes for semantic retrieval (v0.7.0)
----------------------------------------------------------------------
-- Used by brain-consult (Tier 2 retrieval), brain-map (hybrid queries),
-- brain-consolidate (topic relevance).
--
-- This is a content-sync table: it mirrors data from sinapses
-- and must be rebuilt after any INSERT/UPDATE via:
--   INSERT INTO sinapses_fts(sinapses_fts) VALUES('rebuild');
--
-- Backward compatible: if FTS5 is not available, skills fall back to
-- LIKE queries on structured fields (region, tags).

CREATE VIRTUAL TABLE IF NOT EXISTS sinapses_fts USING fts5(
    id UNINDEXED,
    title,
    content,
    tags,
    content=sinapses,
    content_rowid=rowid
);
