-- brain.db — Canonical SQLite Schema
-- Source of truth for all brain-map, brain-lesson, brain-consolidate queries.
-- Generated by brain-init Phase 7 (python scripts/build_brain_db.py).
-- If a skill query fails, check this schema first.

----------------------------------------------------------------------
-- SINAPSES — Curated domain knowledge nodes
----------------------------------------------------------------------
-- Each sinapse is a markdown file indexed into this table.
-- Regions map to the .brain/ directory structure:
--   'hippocampus'       → .brain/hippocampus/*.md
--   'cortex/backend'    → .brain/cortex/backend/*.md
--   'cortex/frontend'   → .brain/cortex/frontend/*.md
--   'cortex/database'   → .brain/cortex/database/*.md
--   'cortex/infra'      → .brain/cortex/infra/*.md
--   'sinapses/'         → .brain/sinapses/*.md (cross-cutting)

CREATE TABLE IF NOT EXISTS sinapses (
    id            TEXT PRIMARY KEY,          -- e.g., 'hippocampus-architecture', 'cortex-backend-index'
    file_path     TEXT NOT NULL,             -- relative path from .brain/ root
    title         TEXT NOT NULL,
    region        TEXT NOT NULL,             -- directory-based: 'hippocampus', 'cortex/backend', 'sinapses/'
    tags          TEXT DEFAULT '[]',         -- JSON array of string tags
    links         TEXT DEFAULT '[]',         -- JSON array of related sinapse ids
    content       TEXT,                      -- full markdown content (for search/condensing)
    weight        REAL NOT NULL DEFAULT 0.50,-- 0.0–1.0, higher = more relevant. Adjusted by brain-consolidate.
    last_accessed TEXT,                      -- ISO8601 datetime, updated on each brain-map load
    usage_count   INTEGER NOT NULL DEFAULT 0,-- incremented each time loaded into a context packet
    created_at    TEXT NOT NULL,             -- ISO8601
    updated_at    TEXT NOT NULL              -- ISO8601
);

CREATE INDEX IF NOT EXISTS idx_sinapses_region ON sinapses(region);
CREATE INDEX IF NOT EXISTS idx_sinapses_weight ON sinapses(weight DESC);

----------------------------------------------------------------------
-- SINAPSE_LINKS — Directed edges between sinapses
----------------------------------------------------------------------
-- Represents backlinks / references between knowledge nodes.
-- Used by brain-map Tier 2 (backlink enrichment) and Tier 3 (on-demand expansion).

CREATE TABLE IF NOT EXISTS sinapse_links (
    source_id TEXT NOT NULL,                -- FK → sinapses.id (the sinapse containing the reference)
    target_id TEXT NOT NULL,                -- FK → sinapses.id (the sinapse being referenced)
    PRIMARY KEY (source_id, target_id),
    FOREIGN KEY (source_id) REFERENCES sinapses(id) ON DELETE CASCADE,
    FOREIGN KEY (target_id) REFERENCES sinapses(id) ON DELETE CASCADE
);

CREATE INDEX IF NOT EXISTS idx_sinapse_links_source ON sinapse_links(source_id);
CREATE INDEX IF NOT EXISTS idx_sinapse_links_target ON sinapse_links(target_id);

----------------------------------------------------------------------
-- LESSONS — Failure-derived knowledge with lifecycle
----------------------------------------------------------------------
-- Created by brain-lesson. Stored in distributed directories:
--   cortex/<domain>/lessons/  → domain-specific lessons
--   lessons/cross-domain/     → lessons spanning multiple domains
--   lessons/inbox/            → unclassified, pending domain assignment
--   lessons/archived/         → no longer active
--
-- Promoted lessons (status = 'promoted') have their rule added to
-- hippocampus/conventions.md by brain-consolidate after developer approval.
--
-- DEFAULT RETRIEVAL: Queries should normally exclude 'archived' and
-- 'superseded' lessons unless explicitly looking at history.

CREATE TABLE IF NOT EXISTS lessons (
    id               TEXT PRIMARY KEY,             -- e.g., 'lesson-00037'
    file_path        TEXT NOT NULL,                -- relative path from .brain/ root
    title            TEXT NOT NULL,
    domain           TEXT NOT NULL,                -- backend | frontend | database | infra | analytics
    scope            TEXT NOT NULL DEFAULT 'domain-local', -- domain-local | cross-domain
    affected_domains TEXT DEFAULT '[]',            -- JSON array, populated only if scope = cross-domain
    tags             TEXT DEFAULT '[]',            -- JSON array of string tags
    severity         TEXT NOT NULL DEFAULT 'medium',-- critical | high | medium | low
    status           TEXT NOT NULL DEFAULT 'draft',-- draft | active | promotion_candidate | promoted | archived | superseded
    parent_synapse   TEXT,                         -- sinapse.id if this lesson extends a known pattern
    recurrence_count INTEGER NOT NULL DEFAULT 1,
    promotion_candidate INTEGER NOT NULL DEFAULT 0,-- 1 if flagged by brain-lesson Step 4
    created_from     TEXT,                         -- task-id (YYYY-MM-DD-<slug>) that produced this lesson
    source_agent     TEXT DEFAULT 'brain-lesson',  -- which skill created it
    supersedes       TEXT,                         -- lesson.id if this replaces an older lesson
    superseded_by    TEXT,                         -- lesson.id if a newer lesson replaced this one
    confidence       TEXT DEFAULT 'medium',        -- high | medium | low
    root_cause_type  TEXT,                         -- misuse | gap | regression | assumption
    evidence         TEXT,                         -- brief evidence description
    weight           REAL NOT NULL DEFAULT 0.50,   -- for ordering in brain-map Tier 1 lesson loading
    related_links    TEXT DEFAULT '[]',            -- JSON array of related lesson or sinapse ids
    created_at       TEXT NOT NULL,
    updated_at       TEXT NOT NULL
);

CREATE INDEX IF NOT EXISTS idx_lessons_domain ON lessons(domain);
CREATE INDEX IF NOT EXISTS idx_lessons_status ON lessons(status);
CREATE INDEX IF NOT EXISTS idx_lessons_severity ON lessons(severity);
CREATE INDEX IF NOT EXISTS idx_lessons_domain_tags ON lessons(domain, tags);

----------------------------------------------------------------------
-- CONSOLIDATION_LOG — Tracks brain-consolidate runs
----------------------------------------------------------------------
-- One row per consolidation cycle. Used to determine "since last consolidate".

CREATE TABLE IF NOT EXISTS consolidation_log (
    cycle_number   INTEGER PRIMARY KEY AUTOINCREMENT,
    tasks_reviewed INTEGER NOT NULL DEFAULT 0,
    proposals_approved INTEGER NOT NULL DEFAULT 0,
    proposals_rejected INTEGER NOT NULL DEFAULT 0,
    escalations_surfaced INTEGER NOT NULL DEFAULT 0,
    sinapses_reweighted INTEGER NOT NULL DEFAULT 0,
    created_at     TEXT NOT NULL
);
